### ISSUE TITLE
ND100 does not build on macOS Ventura 13.3 with latest Xcode

### ISSUE THREAD

**Issue by psco** [open-simh/simh#210]
I get:

```
simh % make nd100

...

***
*** nd100 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple clang version 14.0.3.
*** - Per simulator tests will be run.
***
*** git commit id is 75e79a4da813606d8f0bb0a0a5bd280f46bbe508.
*** git commit time is 2023-04-01T20:23:23-1000.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=75e79a4da813606d8f0bb0a0a5bd280f46bbe508 -DSIM_GIT_COMMIT_TIME=2023-04-01T20:23:23-1000  -DSIM_COMPILER="Apple clang version 14.0.3" -DSIM_BUILD_TOOL=simh-makefile -I . -Werror -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SYS_IOCTL -DSIM_HAVE_DLOPEN=dylib -DHAVE_EDITLINE -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./ND100/nd100_sys.c ./ND100/nd100_cpu.c ./ND100/nd100_floppy.c ./ND100/nd100_stddev.c ./ND100/nd100_mm.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./ND100 -o BIN/nd100 -lpthread -lpcre -ledit -lpng -lz  
./ND100/nd100_cpu.c:1555:1: error: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
ffs(mask)
^
1 error generated.
make: *** [BIN/nd100] Error 1
simh % gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
simh % 

```

PS: Using my XCode project building all simulators I get more than 2'000 warnings. Let's hope that Apple does not decide to promote some of them to warnings shown by default. Maybe `WARNINGS=ALLOWED` should be the default.

**Comment by pkoning2** [comment]
That's a common warning in GCC as well, at least if you use -Wall as many people do.  The two solutions are (a) add a declaration (in a .h file) or, for ones like this that are only used in one file, make them static instead.

**Comment by ragge0** [comment]
This is a small bug, by accident a function was left that is not used.

**Comment by psco** [comment]
Closed via #217
